baseURL = 'https://croshank.github.io/blog/'
languageCode = 'en-us'
title = 'Blog'
theme = 'academic'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
    [markup.goldmark.renderer]
      unsafe = true
